name: godlock_login
description: A new Flutter project.

# Versão mínima do SDK Dart necessária para o projeto
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.3
  provider: ^6.1.2
  go_router: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
