include: package:flutter_lints/recommended.yaml

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - lines_longer_than_80_chars
