name: my_app
description: A new Flutter project for a basic login page

# The version of the application, following the convention of 'major.minor.patch'
version: 1.0.0+1

# Environment specifies the SDK version constraints.
environment:
  sdk: '^3.4.0'

# Dependencies specify the packages that the app needs.
dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies can be listed here.
  cupertino_icons: ^1.0.2  # For iOS style icons

# Dev dependencies are packages needed during development, but not for the app's release build.
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter-specific configurations
flutter:

  # The uses-material-design: true entry tells Flutter to use the Material Design library.
  uses-material-design: true

  # Assets can be listed here, such as images or other resources used in the app.
  # For example:
  # assets:
  #   - assets/images/

  # Fonts can also be specified here.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic